# Generated by Django 2.0 on 2017-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instaworkuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='instaworkuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='instaworkuser',
            name='username',
        ),
        migrations.AddField(
            model_name='instaworkuser',
            name='role',
            field=models.CharField(default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='instaworkuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='instaworkuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instaworkuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
