# Generated by Django 2.0 on 2017-12-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20171222_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaworkuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
